site_name: "Grizzly"

docs_dir: docs/
site_dir: site/
repo_url: "https://github.com/Biometria-se/grizzly"
edit_uri: blob/main/docs/
extra_css:
  - assets/stylesheet.css
extra_javascript:
  - assets/lib/dayjs.min.js
  - assets/lib/dayjs-relative-time.min.js
  - assets/javascript.js

theme:
  name: material
  custom_dir: docs/overrides/
  locale: en
  logo: "assets/logo/grizzly_grasshopper_orange_64px.png"
  favicon: "assets/favicon.ico"
  palette:
    scheme: slate
    primary: brown
    accent: deep orange
  features:
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - section-index
  - grizzly-mkdocs:
      modules:
        grizzly.testdata.variables:
          output: framework/usage/variables/testdata
          extra_frontmatter:
            toc:
              level: 2
  - macros:
      include_dir: .
#  - autorefs
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
          paths:
            - .

markdown_extensions:
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - example.md
  - code_of_conduct.md
  - Framework:
    - Usage:
#      - Tasks:
#          - Clients:
      - Variables:
        - Environment configuration: framework/usage/variables/environment-configuration.md
        - Testdata: grizzly.testdata.variables
        - Templating:
          - framework/usage/variables/templating/index.md
          - Filters: framework/usage/variables/templating/filters.md
#      - Load Users:
#      - Steps:
#        - Background:
#        - Scenario:
    - Changelog: framework/changelog.md
    - Licenses: framework/licenses.md
  - Command Line Interface:
    - Usage:
      - command-line-interface/usage/index.md
      - Metadata: command-line-interface/usage/metadata.md
    - Changelog: command-line-interface/changelog.md
    - Licenses: command-line-interface/licenses.md
  - Editor support:
    - editor-support/index.md
    - Language server: editor-support/language-server.md
    - Editors:
      - editor-support/editors/index.md
      - Visual Studio Code: editor-support/editors/vscode.md
    - Changelog: editor-support/changelog.md
    - Licenses: editor-support/licenses.md
